name: RuffFix Lint and Format
description: Lint and format Python code using Ruff
author: Yuhesh Pandian
branding:
  icon: "zap"
  color: "black"

inputs:
  python-version:
    description: Python version to use
    required: false
    default: "3.x"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Ruff
      run: pip install ruff
      shell: bash

    - name: Run Ruff Linter
      run: ruff check .
      shell: bash

    - name: Run Ruff Formatter
      run: ruff format .
      shell: bash

    - name: Commit changes (if any)
      run: |
        git init
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        if ! git diff --cached --quiet; then
          git commit -m 'Chore: auto-format code using Ruff'
          git pull --rebase
          git push
        fi
      shell: bash
      continue-on-error: true
