name: 'RuffFix'
description: 'Lint and Format Python code using Ruff'
author: 'Yuhesh Pandian'

inputs:
  mode:
    description: 'Choose between lint, format, or all'
    required: false
    default: 'all'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Ruff
      run: pip install --no-cache-dir --upgrade ruff
      shell: bash

    - name: Run Ruff based on mode
      shell: bash
      run: |
        echo "🔍 Running Ruff in '${{ inputs.mode }}' mode"
        case "${{ inputs.mode }}" in
          lint)
            ruff check .
            ;;
          format)
            ruff format .
            ;;
          all)
            ruff check .
            ruff format .
            ;;
          *)
            echo "❌ Invalid mode: '${{ inputs.mode }}'. Use: lint, format, or all."
            exit 1
            ;;
        esac

branding:
  icon: "zap"
  color: "gray-dark"
